# Generated by Django 6.0 on 2026-01-01 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offensive_style', models.CharField(blank=True, choices=[('balanced', 'Balanced'), ('motion', 'Motion'), ('drive', 'Drive'), ('set', 'Set'), ('early', 'Early')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coached_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gaa.gaaclub')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
