# Generated by Django 6.0 on 2026-01-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaa', '0002_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('RB', 'Right Back'), ('FB', 'Full Back'), ('LB', 'Left Back'), ('RHB', 'Right Half Back'), ('CB', 'Center Back'), ('LHB', 'Left Half Back'), ('RMF', 'Right Midfield'), ('LMF', 'Left Midfield'), ('RHF', 'Right Half Forward'), ('CHF', 'Center Half Forward'), ('LHF', 'Left Half Forward'), ('RCF', 'Right Corner Forward'), ('CF', 'Full Forward'), ('LCF', 'Left Corner Forward')], max_length=5)),
                ('overall_rating', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('skill', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='gaa.gaaclub')),
            ],
        ),
    ]
