# Generated by Django 6.0 on 2026-01-02 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaa', '0004_lineup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='coached_club',
        ),
        migrations.RemoveField(
            model_name='season',
            name='user',
        ),
        migrations.DeleteModel(
            name='Lineup',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
