# Generated by Django 6.0 on 2026-01-04 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaa', '0005_remove_season_coached_club_remove_season_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offensive_style', models.CharField(choices=[('BAL', 'Balanced'), ('ATT', 'Attacking'), ('DEF', 'Defensive')], default='BAL', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coached_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaa.gaaclub')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='season', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
